#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Keigo Shishido 
#SPDX-License-Identifier: BSD-3-Clause

import sys

a = 0
b = 0
c = 1
d = 1

for line in sys.stdin:
     a += float(line)
     b -= float(line)
     c *= float(line)
     d /= float(line)

print(a)
print(b)
print(c)
print(d)
